resilience4j:
  circuitbreaker:
    instances:
      ExternalService:
        sliding-window-size: '10'
        sliding-window-type: count_based
        failure-rate-threshold: '50'
        minimum-number-of-calls: '5'
        permitted-number-of-calls-in-half-open-state: '3'
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: 'true'
  retry:
    instances:
      RetryApi:
        max-attempts: '3'
        wait-duration: 1s
  timelimiter:
    instances:
      TimeLimiterApi:
        timeout-duration: 2s
        cancel-running-future: 'true'
  bulkhead:
    instances:
      BulkheadApi:
        max-wait-duration: '1'
        max-concurrent-calls: '3'
  ratelimiter:
    instances:
      RateLimiterApi:
        timeout-duration: 0s
        event-consumer-buffer-size: '50'
        register-health-indicator: 'true'
        limit-for-period: '5'
        subscribe-for-events: 'true'
        limit-refresh-period: 60s
        allow-health-indicator-to-fail: 'true'
      
        
        
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
    org.springframework.web: DEBUG
